/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class AdminGetUsersResponseAllOfUsers {
    'id': number;
    'username': string;
    'email': string;
    'name': string;
    'photo'?: string;
    'created': Date;
<<<<<<< HEAD:sdk/studio/sdk/model/adminGetUsersResponseAllOfUsers.ts
    'lastSeen'?: Date;
    'activated'?: boolean;
    'fromEvaluation'?: boolean;
    'tier'?: AdminGetUsersResponseAllOfUsersTierEnum;
=======
    'added': Date;
    'email': string;
    'role': OrganizationUserRoleEnum;
    'isEdgeImpulseStaff': boolean;
    'projectCount': number;
    'datasets': Array<string>;
>>>>>>> parent of 840c0ea (Release v1.13.10):sdk/studio/model/organizationUser.ts

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "photo",
            "baseName": "photo",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "lastSeen",
            "baseName": "lastSeen",
            "type": "Date"
        },
        {
            "name": "activated",
            "baseName": "activated",
            "type": "boolean"
        },
        {
<<<<<<< HEAD:sdk/studio/sdk/model/adminGetUsersResponseAllOfUsers.ts
            "name": "fromEvaluation",
            "baseName": "from_evaluation",
            "type": "boolean"
        },
        {
            "name": "tier",
            "baseName": "tier",
            "type": "AdminGetUsersResponseAllOfUsersTierEnum"
=======
            "name": "projectCount",
            "baseName": "projectCount",
            "type": "number"
        },
        {
            "name": "datasets",
            "baseName": "datasets",
            "type": "Array<string>"
>>>>>>> parent of 840c0ea (Release v1.13.10):sdk/studio/model/organizationUser.ts
        }    ];

    static getAttributeTypeMap() {
        return AdminGetUsersResponseAllOfUsers.attributeTypeMap;
    }
}


export type AdminGetUsersResponseAllOfUsersTierEnum = 'free' | 'pro' | 'enterprise';
export const AdminGetUsersResponseAllOfUsersTierEnumValues: string[] = ['free', 'pro', 'enterprise'];
