/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ImageInputScaling } from './imageInputScaling';
import { KerasModelLayer } from './kerasModelLayer';
import { KerasModelMetadataMetrics } from './kerasModelMetadataMetrics';
import { KerasModelTypeEnum } from './kerasModelTypeEnum';
import { ObjectDetectionLastLayer } from './objectDetectionLastLayer';

export class KerasModelMetadataAllOf {
    /**
    * Date when the model was trained
    */
    'created': Date;
    /**
    * Layers of the neural network
    */
    'layers': Array<KerasModelLayer>;
    /**
    * Labels for the output layer
    */
    'classNames': Array<string>;
    /**
    * Original labels in the dataset when features were generated, e.g. used to render the feature explorer.
    */
    'labels': Array<string>;
    /**
    * The types of model that are available
    */
    'availableModelTypes': Array<KerasModelTypeEnum>;
    'recommendedModelType': KerasModelTypeEnum;
    /**
    * Metrics for each of the available model types
    */
    'modelValidationMetrics': Array<KerasModelMetadataMetrics>;
    'hasTrainedModel': boolean;
<<<<<<< HEAD:sdk/studio/sdk/model/kerasModelMetadataAllOf.ts
    'mode': KerasModelMetadataAllOfModeEnum;
    'objectDetectionLastLayer'?: ObjectDetectionLastLayer;
    'imageInputScaling': ImageInputScaling;
=======
>>>>>>> parent of 840c0ea (Release v1.13.10):sdk/studio/model/kerasModelMetadataAllOf.ts

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "layers",
            "baseName": "layers",
            "type": "Array<KerasModelLayer>"
        },
        {
            "name": "classNames",
            "baseName": "classNames",
            "type": "Array<string>"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<string>"
        },
        {
            "name": "availableModelTypes",
            "baseName": "availableModelTypes",
            "type": "Array<KerasModelTypeEnum>"
        },
        {
            "name": "recommendedModelType",
            "baseName": "recommendedModelType",
            "type": "KerasModelTypeEnum"
        },
        {
            "name": "modelValidationMetrics",
            "baseName": "modelValidationMetrics",
            "type": "Array<KerasModelMetadataMetrics>"
        },
        {
            "name": "hasTrainedModel",
            "baseName": "hasTrainedModel",
            "type": "boolean"
<<<<<<< HEAD:sdk/studio/sdk/model/kerasModelMetadataAllOf.ts
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "KerasModelMetadataAllOfModeEnum"
        },
        {
            "name": "objectDetectionLastLayer",
            "baseName": "objectDetectionLastLayer",
            "type": "ObjectDetectionLastLayer"
        },
        {
            "name": "imageInputScaling",
            "baseName": "imageInputScaling",
            "type": "ImageInputScaling"
=======
>>>>>>> parent of 840c0ea (Release v1.13.10):sdk/studio/model/kerasModelMetadataAllOf.ts
        }    ];

    static getAttributeTypeMap() {
        return KerasModelMetadataAllOf.attributeTypeMap;
    }
}

<<<<<<< HEAD:sdk/studio/sdk/model/kerasModelMetadataAllOf.ts

export type KerasModelMetadataAllOfModeEnum = 'classification' | 'regression' | 'object-detection' | 'visual-anomaly';
export const KerasModelMetadataAllOfModeEnumValues: string[] = ['classification', 'regression', 'object-detection', 'visual-anomaly'];
=======
>>>>>>> parent of 840c0ea (Release v1.13.10):sdk/studio/model/kerasModelMetadataAllOf.ts
