/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class UpdateOrganizationTransformationBlockRequest {
    'name'?: string;
    'dockerContainer'?: string;
    /**
    * Whether to pass the `--metadata` parameter to the container.
    */
    'indMetadata'?: boolean;
    'description'?: string;
    'cliArguments'?: string;
    'requestsCpu'?: number;
    'requestsMemory'?: number;
    'limitsCpu'?: number;
    'limitsMemory'?: number;
<<<<<<< HEAD:sdk/studio/sdk/model/updateOrganizationTransformationBlockRequest.ts
    'additionalMountPoints'?: Array<TransformationBlockAdditionalMountPoint>;
    'operatesOn'?: UpdateOrganizationTransformationBlockRequestOperatesOnEnum;
    'allowExtraCliArguments'?: boolean;
    /**
    * List of parameters, spec\'ed according to https://docs.edgeimpulse.com/docs/tips-and-tricks/adding-parameters-to-custom-blocks
    */
    'parameters'?: Array<object>;
    /**
    * 15m for 15 minutes, 2h for 2 hours, 1d for 1 day. If not set, the default is 8 hours.
    */
    'maxRunningTimeStr'?: string;
=======
>>>>>>> parent of 840c0ea (Release v1.13.10):sdk/studio/model/updateOrganizationTransformationBlockRequest.ts

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "dockerContainer",
            "baseName": "dockerContainer",
            "type": "string"
        },
        {
            "name": "indMetadata",
            "baseName": "indMetadata",
            "type": "boolean"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "cliArguments",
            "baseName": "cliArguments",
            "type": "string"
        },
        {
            "name": "requestsCpu",
            "baseName": "requestsCpu",
            "type": "number"
        },
        {
            "name": "requestsMemory",
            "baseName": "requestsMemory",
            "type": "number"
        },
        {
            "name": "limitsCpu",
            "baseName": "limitsCpu",
            "type": "number"
        },
        {
            "name": "limitsMemory",
            "baseName": "limitsMemory",
            "type": "number"
<<<<<<< HEAD:sdk/studio/sdk/model/updateOrganizationTransformationBlockRequest.ts
        },
        {
            "name": "additionalMountPoints",
            "baseName": "additionalMountPoints",
            "type": "Array<TransformationBlockAdditionalMountPoint>"
        },
        {
            "name": "operatesOn",
            "baseName": "operatesOn",
            "type": "UpdateOrganizationTransformationBlockRequestOperatesOnEnum"
        },
        {
            "name": "allowExtraCliArguments",
            "baseName": "allowExtraCliArguments",
            "type": "boolean"
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "Array<object>"
        },
        {
            "name": "maxRunningTimeStr",
            "baseName": "maxRunningTimeStr",
            "type": "string"
=======
>>>>>>> parent of 840c0ea (Release v1.13.10):sdk/studio/model/updateOrganizationTransformationBlockRequest.ts
        }    ];

    static getAttributeTypeMap() {
        return UpdateOrganizationTransformationBlockRequest.attributeTypeMap;
    }
}

